In [1]:
import numpy as np

single=np.array([1,2,3,4])
multi=np.array([  [1,2,3],[4,5,6],[7,8,9],[10,11,12]    ])
print(single)
print("\n")
print(multi+5)

[1 2 3 4]


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [0]:
multi.shape    # displays the size of the matrix

(4, 3)

In [0]:
print(multi[0:2])   # Displays limited number of rows

[[1 2 3]
 [4 5 6]]


In [0]:
print(multi[0:,1])   # Display only selected column values from all rows.  x[row-range, column-range],  x[0:all rows  ,  1 range  ]

[ 2  5  8 11]


In [0]:
print(multi[0:,[0,2]])  #  Display the 1st and 3rd column from all rows..  multi(row range,   [column index])

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [0]:
print(multi[[0,3],2:] )   #  Display 1st value of last column of 1st and last row

[[ 3]
 [12]]


In [0]:
print(multi.reshape(3,4))    #  Change the shape of the matrix 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [0]:
np.zeros((2,3))    #  Fill the array with zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((2,3))  #  Fill the array with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.full((2,4), 7 )   #  Fill the array of size 2x4 with 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [0]:
import numpy as np
x=np.array([ [1,2],[3,4],[5,6],[7,8] ])

print(x[1:,[0,1]])
print(x.shape)

[[3 4]
 [5 6]
 [7 8]]
(4, 2)
